#+TITLE: Sheffield COVID-19 forecasts
#+AUTHOR: P.J. Dodd
#+EMAIL: p.j.dodd@sheffield.ac.uk
#+OPTIONS: tex:t
#+LATEX_HEADER: \usepackage{fourier}

* Preamble

This document contains outputs forecasting epidemiological and resource trends based on fitting a transmission model to local case, death and hospital admission data. Numbers and graphs are updated as new data becomes available. The data from local sitreps (ie everything except case data) are not public domain and so this report should be considered sensitive and not onwardly shared.

Please do consider multiple analyses around these questions. Please also consider the estimates of resource implications more caveated because: a) I am less familiar with modelling these; b) the ingredients are likely to be dynamic due to changes in practice and epidemic dynamics.

The most recent case data used in this report is from:
#+INCLUDE: "./data/maxdate_cases.txt"

The most recent sitrep data used in this report is from:
#+INCLUDE: "./data/maxdate_sitrep.txt"

* Summary

The effective reproduction number is estimated to be below 1; the peak in admissions and cases is estimated to be in the recent past and the deaths and bed use are forecast to be decreasing from between now and the start of May. 

** Recent changes (most recent first)

<2020-05-08 Fri>
- Use of lockdown date as change point
- Change to trend graph: including only Sheffield and doubling prior to lockdown
- After 2020-04-26, COVID bed counts are based on inflow/outflows
- Bed proportions based on data between 2020-04-07 and 2020-04-21
- O2 proportions based on data between 2020-04-09 and 2020-04-25
- Improved delay to death/hospitalisation calculation
- Discharge from hospital rate now changes over time


<2020-04-20 Mon>
- Changing to use revised PHE case data (ie by test date). More work is now in the processing script, and the case data need to be manually downloaded and placed in the same folder as the most recent sitrep.

<2020-04-08 Wed>

- In output IncData.csv, "hosp" variable has been renamed "admissions"
- Additional graph to clarify trends in data (Figure [[fig-inctrends]])

<2020-04-07 Tue>

- _Infectious period changed_ from 4.6 to 2.9 days, following [[https://doi.org/10.1016/S1473-3099(20)30144-4][Kucharski et al]]. This leads to somewhat lower initial $R_0$ estimates (nearer 3 than 4), and lower peaks.
- _Change in sensitivity analysis on proportion of cases confirmed_ from $2\times$ basecase (15%) to half of basecase (3.75%), since the 15% assumption consistently fits badly to mortality data, and feels unrealistic. The 3.75% analysis has earlier peaks than base case by 2-3 weeks.


* Results


** Overall trends

 A decrease in the rate of growth was visible locally after the lockdown (red dashed line Figure [[fig-trends]]). Data on the daily incidence of quantities used as calibration targets are shown in Figure [[fig-inctrends]].

 #+CAPTION: Cumulative confirmed cases nationally and locally. Red dashed line is where a change in gradient is visible shortly after lockdown
 #+attr_html: :width 100%
 #+name: fig-trends
 #+attr_latex: :width \textwidth :placement [h!]
 [[./figs/Trends.pdf]]


 #+CAPTION: Data on daily incidence of quantities used as calibration targets
 #+attr_html: :width 100%
 #+name: fig-inctrends
 #+attr_latex: :width \textwidth :placement [h!]
 [[./figs/IncData.pdf]]


** Parameter estimates

Our estimate for $R_0$ with 7.5% of cases assumed confirmed is:
#+INCLUDE: "./data/Rzero.txt"
Our estimate for $R_0$ with 3.8% of cases assumed confirmed is:
#+INCLUDE: "./data/Rzero2.txt"

This compares with an $R_0$ estimate for the UK in the  [[https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/report-13-europe-npi-impact/][Imperial report 13]] report of a little below 4.

Our estimate for the reduction in transmission from lockdown with 7.5% of cases assumed confirmed is:
#+INCLUDE: "./data/Effect.txt"
percent; with 3.8% of cases confirmed it is: 
#+INCLUDE: "./data/Effect2.txt"
percent.

This is within the uncertain estimate of lockdown efficacy for 11 European countries in the [[https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/report-13-europe-npi-impact/][Imperial report 13]] & the effect estimates based on changes in social contact patterns reported in an [[https://cmmid.github.io/topics/covid19/current-patterns-transmission/comix-impact-of-physical-distance-measures-on-transmission-in-the-UK.html][LSHTM study]].

This implies an estimate for the current net reproduction number with 7.5% of cases assumed confirmed is:
#+INCLUDE: "./data/Rnet.txt"
; with 3.8% of cases confirmed it is: 
#+INCLUDE: "./data/Rnet2.txt"

In addition we estimate the fraction of cases to needing hospitalisation to be:
#+INCLUDE: "./data/HFR.txt"
percent; with 3.8% of cases confirmed it is: 
#+INCLUDE: "./data/HFR2.txt"
percent.

This compares with an estimate using age-specific rates from literature, weighted by Sheffield demography of
#+INCLUDE: "./data/HFRlit.txt"
percent.

** Projected daily cases, hospitalisations, deaths

Corresponding to a net reproduction number above 1, the local epidemic is forecast to be growing. Figure [[fig-inclog]] shows the data used in fitting, which is clearer on a log scale. Figure [[fig-increal]] shows these projections on a real scale. Analyses were performed under a basecase assumption that 7.5% of cases are confirmed and as a sensitivity analysis, half this value (ie 3.75%).

 #+CAPTION: Fit to confirmed cases, hospitalisations and deaths in Sheffield (log scale)
 #+attr_html: :width 100%
 #+name: fig-inclog
 #+attr_latex: :width \textwidth :placement [h!]
 [[./figs/IncLog.pdf]]

 #+CAPTION: Projected confirmed cases, hospitalisations and deaths in Sheffield (real scale)
 #+attr_html: :width 100%
 #+name: fig-increal
 #+attr_latex: :width \textwidth :placement [h!]
 [[./figs/IncReal.pdf]]

** Projected resource utilisation

We used estimates of hospital stay length and fractions of COVID patients in different bed types and requiring different breathing assistance to project resource requirements. See Figure [[fig-prevlog]], on a log scale. The datapoints plotted (inpatient prevalence and ITU prevalence) are from the sitrep data are not fitted to directly, but informed by proportions and stay lengths analyses of sitrep data. Figure [[fig-prevreal]] shows resource requirements on a real scale.

 #+CAPTION: Projected resource use of Sheffield (log scale)
 #+attr_html: :width 100%
 #+name: fig-prevlog
 #+attr_latex: :width \textwidth :placement [h!]
 [[./figs/PrevLog.pdf]]

 #+CAPTION: Projected resource use of Sheffield (real scale)
 #+attr_html: :width 100%
 #+name: fig-prevreal
 #+attr_latex: :width \textwidth :placement [h!]
 [[./figs/PrevReal.pdf]]

* Methods

** Code and output availability

The code for the analyses and this report are updated and available at [[https://github.com/petedodd/CV19SHF]].

The updated report itself and also the CSV files of estimates are available at:
#+INCLUDE: "./data/dataurl.txt"

Data sources and analyses for the model are described in the following subsections. The model specification and fitting is described in Section \ref{sec-appendix}.

** COVID testing data

The concern with testing is that as only a minority of infections are confirmed, this could bias estimates. We use a basecase assumption that 7.5% of infections in the UK have been confirmed, based on this analysis: [[https://cmmid.github.io/topics/covid19/severity/global_cfr_estimates.html]]. We also consider a sensitivity analysis of half this value as Sheffield is understood to have tested more extensively.

While most results are robust against constant under-ascertainment, trends in testing (eg the planned ramping up) will introduce bias. At the moment this is not accounted for as there is not strong evidence of a trend (see Figure [[fig-tests]]). This issue motivates including hospitalisations and particularly deaths as calibration targets. If evidence of testing trends becomes visible, we will attempt to adjust for this in using case data.

 #+CAPTION: COVID testing volumes and proportion positive.
 #+attr_html: :width 100%
 #+name: fig-tests
 #+attr_latex: :width \textwidth :placement [h!]
 [[./figs/LabTests.pdf]]

** Delay estimates
\label{delays}
*** Case to hospitalisation or death

To generate estimates of delays from cases to hospitalisation and death, we used linear regression of the log cumulative cases, hospital admissions and deaths with shared slope but different intercepts. These results generated delays of  
#+INCLUDE: "./data/dC2H.txt" 
days from case-to-hospital admission and  
#+INCLUDE: "./data/dC2D.txt"
days from case-to-death. See Figure [[fig-delays]] for approximate alignments. These compare to estimates used in Imperial report 9 of 10 days and 20 days respectively.

NB we have take hospital admission (in the sitrep data) to include admission of COVID positive patients and positive COVID testing of existing inpatients.


 #+CAPTION: Log of cumulative cases, hospitalisations and deaths; with alignments by delay.
 #+attr_html: :width 100%
 #+name: fig-delays
 #+attr_latex: :width \textwidth :placement [h!]
 [[./figs/Delays.pdf]]



*** Hospital stays

To determine mean hospital stays related to COVID locally, we calculated the mean rates of discharge and death among COVID inpatients from the sitrep data. There are trends in discharge rates, see Figure [[fig-outrates]]. A smoothed rate of discharge over time was used, see Figure [[fig-outrates2]], with last-one-carried forward for forecasts.
 #+INCLUDE: "./data/meanstay.txt"
days. This compares with 10 days for critical care patients and 7 days for other patients assumed in Imperial report 9.


 #+CAPTION: Raw rates of discharge and death among COVID inpatients (red dashed line = last 7 days)
 #+attr_html: :width 100%
 #+name: fig-outrates
 #+attr_latex: :width \textwidth :placement [h!]
 [[./figs/OutRates.pdf]]





 #+CAPTION: Smoothed rates of discharge among COVID inpatients
 #+attr_html: :width 100%
 #+name: fig-outrates2
 #+attr_latex: :width \textwidth :placement [h!]
 [[./figs/outrate.pdf]]


** Bed type and breathing assistance

To parametrize the number of beds of each type used and the use of various types of breathing assistance, we used the simple approach of multiplying the number hospitalised cases by the proportion of inpatients with COVID observed in different bed types (Figure [[fig-beds]]) or requiring different types of breathing assistance (Figure [[fig-O2]]). We used averages from the most recent 7 days of sitrep data. However, trends are visible in bed type used and practice may change if resource limits are approached.

 #+CAPTION: The proportion of COVID inpatients in different bed types (red dashed line = last 7 days)
 #+attr_html: :width 100%
 #+name: fig-beds
 #+attr_latex: :width \textwidth :placement [h!]
 [[./figs/BedProps.pdf]]

 #+CAPTION: The proportion of COVID inpatients requiring different breathing assistance (red dashed line = last 7 days)
 #+attr_html: :width 100%
 #+name: fig-O2
 #+attr_latex: :width \textwidth :placement [h!]
 [[./figs/Oprops.pdf]]
 
** Parameters from literature

Most parameters are contained in the following table, although not all these are used in the current version. The Verity IFRs are used, but the parameters relating to hospitalisation are not used.

|  ages | demo | sympto | symptohosp | hospcc |  IFR |
|-------+------+--------+------------+--------+------|
|   0-9 | 0.11 |     66 |        0.1 |      5 | 0.00 |
| 10-19 | 0.12 |     66 |        0.3 |      5 | 0.01 |
| 20-29 | 0.19 |     66 |        1.2 |      5 | 0.00 |
| 30-39 | 0.14 |     66 |        3.2 |      5 | 0.08 |
| 40-49 | 0.12 |     66 |        4.9 |      6 | 0.15 |
| 50-59 | 0.12 |     66 |       10.2 |     12 | 0.60 |
| 60-69 | 0.09 |     66 |       16.6 |     27 | 2.20 |
| 70-79 | 0.07 |     66 |       24.3 |     43 | 5.10 |
|   80+ | 0.04 |     66 |       27.3 |     71 | 9.30 |




* Appendix: modelling details
\label{sec-appendix}


The model is an SEIR (susceptible-latent-infected-recovered) model using latent period ($1/\nu$) 5.2 days and infectious period ($1/\nu_2$) 2.9 days, following Kucharski et al  [[https://doi.org/10.1016/S1473-3099(20)30144-4]] (see supplement table S1):

$$\frac{\mathrm{d}S}{\mathrm{d}t} = -\beta(t)\frac{SI}{N} $$
$$\frac{\mathrm{d}E}{\mathrm{d}t} =+\beta(t)\frac{SI}{N} -\nu E$$
$$\frac{\mathrm{d}I}{\mathrm{d}t} =\nu E - \nu_2 I$$
$$\frac{\mathrm{d}R}{\mathrm{d}t} = \nu_2 I$$

The model is not age-structured. For IFR, a mean of the age-specific IFRs was taken using the proportion of the Sheffield population in each age-group.

The transmission term $\beta(t)$ was taken to be a piecewise constant function whose value changes at the time-point corresponding to gradient change in case data (shown with vertical dashed red lines in projection graphs).

Incidence of confirmed cases in this model was taken as proportional to $\nu E$.

Auxilliary states $sick$ and $dying$ were used to calculate the incidence of hospitalisation and death:

$$\frac{\mathrm{d}(sick)}{\mathrm{d}t} = \nu E\times HR - sick/d_h$$
$$\frac{\mathrm{d}(dying)}{\mathrm{d}t} = \nu E\times IFR - dying/d_d$$

Here $IFR$ is the infection fatality rate and $HR$ is the fraction of cases hospitalised. (The delays $d_h$ and $d_d$ are determined from a separate analysis - see Section \ref{delays}). The incidence of death is then $dying/d_d$ and the incidence of hospitalisation is $sick/d_h$.

Finally, prevalence of hospitalisation was determined by an additional equation:
$$\frac{\mathrm{d}(hosp)}{\mathrm{d}t} = sick/d_h - hosp/d_{h2o}$$
where the mean stay $d_{h2o}$ is determined in Section \ref{delays}. The incidence of hospitalisation is $sick/d_h$.


A likelihood is specified by assuming Poisson counts for daily case, admission and death counts, with parameters given by the rates from the ODEs. Parameters corresponding to $R_0$, the reduction in $\beta$ due to lockdown, the initial number infected, and the proportion of cases hospitalised ($HR$ above) were fitted. Uncertainty intervals were constructed from 200 simulations of parameters drawn from a multivariate normal approximation to the likelihood.







